#CONFIG_GPIO=y
#CONFIG_LOG=y

#CONFIG_BLINK_SLEEP_250MS=y
#CONFIG_BLINK_SLEEP_TIME_MS=2000 .> wrong , error

CONFIG_SENSOR=y
CONFIG_GPIO=y
CONFIG_PRINTK=y
CONFIG_PRINTK_SYNC=y

# Enable Zephyr Shell Subsystem
CONFIG_SHELL=y
CONFIG_SENSOR_SHELL=n  # Disable factory sensor shell to prevent command name conflicts


# Route the Interactive Shell directly into your current terminal 
CONFIG_UART_NATIVE_PTY_0_ON_STDINOUT=y
